### ISSUE TITLE
[question/request] can delta do manual update?

### ISSUE THREAD

**Issue by lewislepton** [furusystems/Delta#8]
just to ask. could or can delta do manual update.

asking as I have tried different tweens within different states with different updates etc. but want to not have a global acting tween update. only fires off when a state is using a tween for that state

**Comment by Sunjammer** [comment]
The TweenAction and TweenSequence step function is public, so it's conceivable you can just step yourself to your heart's content, though I haven't tried it. What you can do is also create TweenChannels yourself. Delta.channel(id) gives you a TweenChannel instance that has all the usual Delta jazz on it, and as long as you don't step on Delta itself you can step your individual channels in whatever way you want.
